### ISSUE TITLE
Predictions per pair during evaluation

### ISSUE THREAD

**Issue by nickgkan** [facebookresearch/Large-Scale-VRD#3]
Hi, great work! Thanks for the code release.

When evaluating on VG200, how many predictions do you keep per pair? For example on VRD, you report results for three different values for the hyperparameter k. Is k fixed in VG200's case and if yes, in what value?

Thank you in advance!

**Comment by jz462** [comment]
@nickgkan Thank you bringing up this important question! In VG200 we used k=1 as shown in Table 2 of out paper: https://arxiv.org/pdf/1804.10660.pdf. This is consistent with Table 2 of the Neural Motifs paper, which was the state-of-the-art before our method: https://arxiv.org/pdf/1711.06640v2.pdf.

Our PyTorch version repository is here: https://github.com/jz462/Large-Scale-VRD.pytorch. We will release the code very soon. Please stay tuned!

**Comment by nickgkan** [comment]
@jz462 Ok, thank you, it is clear now! So, using this paper's https://arxiv.org/pdf/1811.09543.pdf terms, scene graph constraint is equivalent to k=1, while no scene graph constraint means k=number of classes or maybe free k, as in your paper https://arxiv.org/pdf/1804.10660.pdf.
